#!bin/bash

export LC_TIME="en_US.UTF-8"

rm -f $HOME/NEWDEV/WRKDIR/*.tex 

./run_ws.sh
./run_wd.sh  
./run_rh.sh
./run_pwv.sh
./run_see.sh  
./run_tau.sh  
./run_glf.sh  
./run_skills.sh

./compile_report.sh

exit 0

