#!bin/bash

export LC_TIME="en_US.UTF-8"
envfile_atmo=$HOME'/SCRIPTS/fate-report-atmo.env'
envfile_astro=$HOME'/SCRIPTS/fate-report-astro.env'

# Source of env file
if [ ! -e $envfile_atmo ]; then
  echo "ops $envfile_atmo does not exist in "`pwd`; exit 1
else 
  source $envfile_atmo
fi
if [ ! -e $envfile_astro ]; then
  echo "ops $envfile_astro does not exist in "`pwd`; exit 1
else
  source $envfile_astro
fi

##############
# HOUSEKEEPING
##############
rm -f $WRKDIR/*.{tex,aux,toc,sty,out,log}
rm -f $WRKDIR/main.{tex,aux,toc,sty,out,log,pdf}
rm -f $WRKDIR/*.png
for dd in night1 day1
do
  if [ -d $WRKDIR/$dd ]; then
    rm -fr $WRKDIR/$dd/*
  else
    mkdir -p $WRKDIR/$dd
  fi
done

########
# NIGHT1
########
echo "+++++++++++++++++++++++"
echo "RUNNING NIGHT1"
echo "+++++++++++++++++++++++"
for var in WS WD RH PWV SEE TAU GLF
do
  ln -sf /home/report/DATA/TREATED/nig1/list_${var}*.txt /home/report/PROG/AR_5GG_1H/
  ln -sf /home/report/DATA/TREATED/nig1/list_${var}*.txt /home/report/PROG/PERSISTENCE/
done
./run_ws.sh     $envfile_astro night 1
./run_wd.sh     $envfile_astro night 1
./run_rh.sh     $envfile_astro night 1
./run_pwv.sh    $envfile_astro night 1
./run_see.sh    $envfile_astro night 1
./run_tau.sh    $envfile_astro night 1
./run_glf.sh    $envfile_astro night 1
./run_skills.sh $envfile_astro night 1

########
# DAY1
########
echo "+++++++++++++++++++++++"
echo "RUNNING DAY1"
echo "+++++++++++++++++++++++"
for var in WS WD RH PWV
do
  ln -sf /home/report/DATA/TREATED/day1/list_${var}*.txt /home/report/PROG/AR_5GG_1H/
  ln -sf /home/report/DATA/TREATED/day1/list_${var}*.txt /home/report/PROG/PERSISTENCE/
done
./run_ws.sh     $envfile_atmo night 1
./run_wd.sh     $envfile_atmo night 1
./run_rh.sh     $envfile_atmo night 1
./run_pwv.sh    $envfile_atmo night 1
./run_skills.sh $envfile_atmo night 1

########
# TABLE WITH OBSERVATIONS
########
./check_logs_obs.sh $envfile_atmo night 1
./check_logs.sh $envfile_atmo night 1

########
# COMPILE LATEX FILE
########
./compile_report.sh $envfile_atmo night 1

########
# EXIT
########
exit 0

